# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Chris P-K
description: > # this means to ignore newlines until "baseurl:"
  Personal blog of Chris Park-Kennaby. Mostly posting my travel photography
  - shot mainly on 35mm film - on a bi-monthly basis. May also write about
  film and technology on occasion.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chrispk.com" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:year/:title/
author:
  name: Chris Park-Kennaby
  email: contact@chrispk.com
contact_page: true
google_tag_manager: GTM-PSXDMN8
google_adsense: ca-pub-1202132740341897
# Build settings
markdown: kramdown
theme: minima
# Changes to specified commit (@<commit_id>) should be refleced in Gemfile
remote_theme: jekyll/minima@6b9b78dad3e5c9f733c901e10287465735b36169
show_excerpts: true
# Minima specific settings, which are only available from Minima 3.0 onward.
minima:
  skin: classic
  social_links:
   - { platform: bluesky,        user_url: "https://bsky.app/profile/chrispk.bsky.social" }
   - { platform: github,         user_url: "https://github.com/chrispk" }
   - { platform: instagram,      user_url: "https://instagram.com/beingchrispy" }
   - { platform: rss,            user_url: "https://chrispk.com/feed.xml" }
  
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-remote-theme

header_pages:
  - about.md

exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - gulpfile.js
  - node_modules
  - git_submodules
  - README.md
  - CNAME
  - Dockerfile